---
openapi: 3.0.1
info:
  title: Weather API
  version: v1
paths:
  "/weather/current":
    get:
      summary: Получить текущую температуру
      tags:
      - Погода
      responses:
        '200':
          description: успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_temp:
                    type: number
                  city_key:
                    type: string
                required:
                - current_temp
                - city_key
  "/weather/historical":
    get:
      summary: Получить почасовую температуру за последние 24ч
      tags:
      - Погода
      responses:
        '200':
          description: успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  temp_history_24h:
                    type: array
                    items:
                      type: object
                      properties:
                        date_time:
                          type: string
                          format: date_time
                        temperature:
                          type: number
                      city_key:
                        type: string
                      required:
                      - date_time
                      - temperature
                required:
                - temp_history_24h
                - city_key
  "/weather/historical/max":
    get:
      summary: Получить максимальную температуру за последние 24ч
      tags:
      - Погода
      responses:
        '200':
          description: успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  max_temp_24h:
                    type: number
                  city_key:
                    type: string
                required:
                - max_temp_24h
                - city_key
  "/weather/historical/min":
    get:
      summary: Получить минимальную температуру за последние 24ч
      tags:
      - Погода
      responses:
        '200':
          description: успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  min_temp_24h:
                    type: number
                  city_key:
                    type: string
                required:
                - min_temp_24h
                - city_key
  "/weather/historical/avg":
    get:
      summary: Получить среднюю температуру за последние 24ч
      tags:
      - Погода
      responses:
        '200':
          description: успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  avg_temp_24h:
                    type: number
                  city_key:
                    type: string
                required:
                - avg_temp_24h
                - city_key
  "/weather/by_time/{timestamp}":
    get:
      summary: Получить температуру ближайшую к переданному timestamp
      tags:
      - Погода
      parameters:
      - name: timestamp
        in: path
        description: Timestamp для поиска температуры погоды по временной метке
        required: true
        schema:
          type: string
      responses:
        '200':
          description: успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  temp_by_time:
                    type: number
                  city_key:
                    type: string
                required:
                - temp_by_time
                - city_key
        '404':
          description: не найдено
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
servers:
- url: http://localhost:3000
  description: weather_local_server
